# Generated by Django 5.2.8 on 2025-12-01 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twobeats_upload', '0002_alter_tag_options_alter_music_music_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twobeats_upload.music', verbose_name='음악')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_likes', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '음악 좋아요',
                'verbose_name_plural': '음악 좋아요',
                'unique_together': {('user', 'music')},
            },
        ),
    ]
