# Generated by Django 5.2.8 on 2025-12-01 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twobeats_upload', '0003_musiclike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='twobeats_upload.video', verbose_name='영상')),
            ],
            options={
                'verbose_name': '영상 좋아요',
                'verbose_name_plural': '영상 좋아요',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
